import Link from "next/link";
import DangerZone from "./danger-zone";
import ThemeToggle from "../theme-toggle";
import { requireScope } from "@/lib/session";
import { store, storeKind } from "@/lib/store";

export const dynamic = "force-dynamic";

export default async function SettingsPage() {
  const { userId } = await requireScope();
  const db = await store.read(userId);
  const hasKey = Boolean(process.env.ANTHROPIC_API_KEY?.trim());

  return (
    <>
      <section>
        <div>
          <div className="eyebrow">Account</div>
          <h1>Settings</h1>
        </div>
        <p className="muted">
          Everything here is local to this browser or to <code>data/db.json</code>. Nothing
          leaves the machine except a planning request, and only when a key is present.
        </p>
      </section>

      <section>
        <article className="card">
          <div className="card-head">
            <div>
              <h3>Appearance</h3>
              <p className="tiny">
                Remembered in <code>localStorage</code> and applied before first paint, so
                there&apos;s no flash of the wrong theme on navigation.
              </p>
            </div>
            <ThemeToggle />
          </div>
        </article>

        <article className="card">
          <div className="card-head">
            <div>
              <h3>Music</h3>
              <p className="tiny">
                Genres, artists, segment lengths and the Spotify connection.
              </p>
            </div>
            <Link href="/music" className="btn btn--ghost">
              Open
            </Link>
          </div>
        </article>

        <article className="card">
          <div className="card-head">
            <div>
              <h3>Planning engine</h3>
              <p className="tiny">
                {hasKey
                  ? "An API key is present, so next week's decisions come from Claude — with the rule engine as the fallback if the response doesn't validate."
                  : "No API key, so decisions come from the deterministic rule engine. Add ANTHROPIC_API_KEY to .env.local to compare the two on identical evidence."}
              </p>
            </div>
            <span className={`chip${hasKey ? " chip--today" : ""}`}>
              {hasKey ? "Model" : "Rules"}
            </span>
          </div>
          <p className="tiny">
            Last plan was generated by the <strong>{db.lastSource ?? "rule"}</strong> path.
            Being able to run both is the point: if the model never disagrees with the rules,
            it isn&apos;t earning its cost.
          </p>
        </article>

        <article className="card">
          <div className="card-head">
            <div>
              <h3>Notifications</h3>
              <p className="tiny">
                The Sunday re-plan and the morning briefing are scheduled outside the app, by
                the training-log MCP server. There is nothing to switch on here yet.
              </p>
            </div>
            <span className="chip">Not built</span>
          </div>
        </article>

        <DangerZone sessionCount={db.sessions.length} />
      </section>
    </>
  );
}
